# Generated by Django 2.2.19 on 2021-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=50)),
                ('car_year', models.IntegerField()),
                ('car_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('car_description', models.TextField()),
            ],
        ),
    ]
