# Generated by Django 2.2.19 on 2021-03-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
